FROM node:12-buster as build

WORKDIR /app

ARG API_URL
ENV API_URL $API_URL

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

FROM fholzer/nginx-brotli:v1.19.1 as prod
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
